export class User {
     data = [
        {
          fullName: 'Mahid Ahmed Tonmoy',
          username: 'mahidtonmoy',
          email: 'mahid.tonmoy@example.com',
          password: 'Onetwothree12@',
          retypePassword: 'Onetwothree12@',
          gender: 'MALE',
          dob: '1998-11-06',
          phoneNumber: '01914274834',
          address: 'Tikatoli, Dhaka, Bangladesh'
        },
        {
          fullName: 'Aisha Rahman',
          username: 'aisharahman',
          email: 'aisha.rahman@example.com',
          password: 'Onetwothree12@',
          retypePassword: 'Onetwothree12@',
          gender: 'FEMALE',
          dob: '1992-04-12',
          phoneNumber: '01911234567',
          address: 'Uttara, Dhaka, Bangladesh'
        },
        {
          fullName: 'Arif Khan',
          username: 'arifkhan',
          email: 'arif.khan@example.com',
          password: 'Onetwothree12@',
          retypePassword: 'Onetwothree12@',
          gender: 'MALE',
          dob: '1989-08-23',
          phoneNumber: '01912345678',
          address: 'Gulshan, Dhaka, Bangladesh'
        },
        {
          fullName: 'Laila Islam',
          username: 'laila.islam',
          email: 'laila.islam@example.com',
          password: 'Onetwothree12@',
          retypePassword: 'Onetwothree12@',
          gender: 'FEMALE',
          dob: '1993-05-17',
          phoneNumber: '01913456789',
          address: 'Banani, Dhaka, Bangladesh'
        },
        {
          fullName: 'Shakib Al Hasan',
          username: 'shakibalhasan',
          email: 'shakib.alhasan@example.com',
          password: 'Onetwothree12@',
          retypePassword: 'Onetwothree12@',
          gender: 'MALE',
          dob: '1988-07-16',
          phoneNumber: '01914567890',
          address: 'Mirpur, Dhaka, Bangladesh'
        },
        {
          fullName: 'Nusrat Jahan',
          username: 'nusratjahan',
          email: 'nusrat.jahan@example.com',
          password: 'Onetwothree12@',
          retypePassword: 'Onetwothree12@',
          gender: 'FEMALE',
          dob: '1995-02-28',
          phoneNumber: '01915678901',
          address: 'Dhanmondi, Dhaka, Bangladesh'
        },
        {
          fullName: 'Saifur Rahman',
          username: 'saifurrahman',
          email: 'saifur.rahman@example.com',
          password: 'Onetwothree12@',
          retypePassword: 'Onetwothree12@',
          gender: 'MALE',
          dob: '1990-11-11',
          phoneNumber: '01916789012',
          address: 'Mohammadpur, Dhaka, Bangladesh'
        },
        {
          fullName: 'Rima Sultana',
          username: 'rimasultana',
          email: 'rima.sultana@example.com',
          password: 'Onetwothree12@',
          retypePassword: 'Onetwothree12@',
          gender: 'FEMALE',
          dob: '1994-09-03',
          phoneNumber: '01917890123',
          address: 'Bashundhara, Dhaka, Bangladesh'
        },
        {
          fullName: 'Tanvir Hossain',
          username: 'tanvirhossain',
          email: 'tanvir.hossain@example.com',
          password: 'Onetwothree12@',
          retypePassword: 'Onetwothree12@',
          gender: 'MALE',
          dob: '1991-03-21',
          phoneNumber: '01918901234',
          address: 'Uttara, Dhaka, Bangladesh'
        },
        {
          fullName: 'Farhana Akter',
          username: 'farhanaakter',
          email: 'farhana.akter@example.com',
          password: 'Onetwothree12@',
          retypePassword: 'Onetwothree12@',
          gender: 'FEMALE',
          dob: '1996-12-05',
          phoneNumber: '01919012345',
          address: 'Gulshan, Dhaka, Bangladesh'
        },
        {
          fullName: 'Imran Ali',
          username: 'imranali',
          email: 'imran.ali@example.com',
          password: 'Onetwothree12@',
          retypePassword: 'Onetwothree12@',
          gender: 'MALE',
          dob: '1987-06-15',
          phoneNumber: '01910123456',
          address: 'Banani, Dhaka, Bangladesh'
        },
        {
          fullName: 'Ritu Parveen',
          username: 'ritaparveen',
          email: 'ritu.parveen@example.com',
          password: 'Onetwothree12@',
          retypePassword: 'Onetwothree12@',
          gender: 'FEMALE',
          dob: '1993-10-10',
          phoneNumber: '01910234567',
          address: 'Dhanmondi, Dhaka, Bangladesh'
        },
        {
          fullName: 'Kamal Uddin',
          username: 'kamaluddin',
          email: 'kamal.uddin@example.com',
          password: 'Onetwothree12@',
          retypePassword: 'Onetwothree12@',
          gender: 'MALE',
          dob: '1985-01-20',
          phoneNumber: '01910345678',
          address: 'Mirpur, Dhaka, Bangladesh'
        },
        {
          fullName: 'Selina Akter',
          username: 'selinaakter',
          email: 'selina.akter@example.com',
          password: 'Onetwothree12@',
          retypePassword: 'Onetwothree12@',
          gender: 'FEMALE',
          dob: '1992-08-08',
          phoneNumber: '01910456789',
          address: 'Mohammadpur, Dhaka, Bangladesh'
        },
        {
          fullName: 'Omar Faruq',
          username: 'omarfaruq',
          email: 'omar.faruq@example.com',
          password: 'Onetwothree12@',
          retypePassword: 'Onetwothree12@',
          gender: 'MALE',
          dob: '1990-02-02',
          phoneNumber: '01910567890',
          address: 'Uttara, Dhaka, Bangladesh'
        },
        {
          fullName: 'Fatima Begum',
          username: 'fatimabegum',
          email: 'fatima.begum@example.com',
          password: 'Onetwothree12@',
          retypePassword: 'Onetwothree12@',
          gender: 'FEMALE',
          dob: '1994-04-25',
          phoneNumber: '01910678901',
          address: 'Gulshan, Dhaka, Bangladesh'
        },
        {
          fullName: 'Rezaul Karim',
          username: 'rezaulkarim',
          email: 'rezaul.karim@example.com',
          password: 'Onetwothree12@',
          retypePassword: 'Onetwothree12@',
          gender: 'MALE',
          dob: '1988-12-30',
          phoneNumber: '01910789012',
          address: 'Banani, Dhaka, Bangladesh'
        },
        {
          fullName: 'Parveen Sultana',
          username: 'parveensultana',
          email: 'parveen.sultana@example.com',
          password: 'Onetwothree12@',
          retypePassword: 'Onetwothree12@',
          gender: 'FEMALE',
          dob: '1991-07-19',
          phoneNumber: '01910890123',
          address: 'Dhanmondi, Dhaka, Bangladesh'
        },
        {
          fullName: 'Arifuzzaman Chowdhury',
          username: 'arifchowdhury',
          email: 'arif.chowdhury@example.com',
          password: 'Onetwothree12@',
          retypePassword: 'Onetwothree12@',
          gender: 'MALE',
          dob: '1990-03-03',
          phoneNumber: '01910901234',
          address: 'Mirpur, Dhaka, Bangladesh'
        },
        {
          fullName: 'Nadia Islam',
          username: 'nadiaislam',
          email: 'nadia.islam@example.com',
          password: 'Onetwothree12@',
          retypePassword: 'Onetwothree12@',
          gender: 'FEMALE',
          dob: '1995-11-11',
          phoneNumber: '01911012345',
          address: 'Mohammadpur, Dhaka, Bangladesh'
        },
        {
          fullName: 'Jamil Uddin',
          username: 'jamiluddin',
          email: 'jamil.uddin@example.com',
          password: 'Onetwothree12@',
          retypePassword: 'Onetwothree12@',
          gender: 'MALE',
          dob: '1986-05-05',
          phoneNumber: '01911123456',
          address: 'Uttara, Dhaka, Bangladesh'
        },
        {
          fullName: 'Shahana Akter',
          username: 'shahanaakter',
          email: 'shahana.akter@example.com',
          password: 'Onetwothree12@',
          retypePassword: 'Onetwothree12@',
          gender: 'FEMALE',
          dob: '1993-09-09',
          phoneNumber: '01911234567',
          address: 'Gulshan, Dhaka, Bangladesh'
        },
        {
          fullName: 'Anik Rahman',
          username: 'anikrahman',
          email: 'anik.rahman@example.com',
          password: 'Onetwothree12@',
          retypePassword: 'Onetwothree12@',
          gender: 'MALE',
          dob: '1990-10-10',
          phoneNumber: '01911345678',
          address: 'Banani, Dhaka, Bangladesh'
        },
        {
          fullName: 'Rokeya Begum',
          username: 'rokeyabegum',
          email: 'rokeya.begum@example.com',
          password: 'Onetwothree12@',
          retypePassword: 'Onetwothree12@',
          gender: 'FEMALE',
          dob: '1992-02-20',
          phoneNumber: '01911456789',
          address: 'Dhanmondi, Dhaka, Bangladesh'
        },
        {
          fullName: 'Kamrul Hassan',
          username: 'kamrulhassan',
          email: 'kamrul.hassan@example.com',
          password: 'Onetwothree12@',
          retypePassword: 'Onetwothree12@',
          gender: 'MALE',
          dob: '1989-06-06',
          phoneNumber: '01911567890',
          address: 'Mirpur, Dhaka, Bangladesh'
        },
        {
          fullName: 'Priya Sen',
          username: 'priyasen',
          email: 'priya.sen@example.com',
          password: 'Onetwothree12@',
          retypePassword: 'Onetwothree12@',
          gender: 'FEMALE',
          dob: '1994-03-15',
          phoneNumber: '01911678901',
          address: 'Mohammadpur, Dhaka, Bangladesh'
        },
        {
          fullName: 'Asif Ali',
          username: 'asifali',
          email: 'asif.ali@example.com',
          password: 'Onetwothree12@',
          retypePassword: 'Onetwothree12@',
          gender: 'MALE',
          dob: '1987-08-08',
          phoneNumber: '01911789012',
          address: 'Uttara, Dhaka, Bangladesh'
        },
        {
          fullName: 'Rupa Sarkar',
          username: 'rupasarkar',
          email: 'rupa.sarkar@example.com',
          password: 'Onetwothree12@',
          retypePassword: 'Onetwothree12@',
          gender: 'FEMALE',
          dob: '1991-12-12',
          phoneNumber: '01911890123',
          address: 'Gulshan, Dhaka, Bangladesh'
        },
        {
          fullName: 'Zahid Hasan',
          username: 'zahidhasan',
          email: 'zahid.hasan@example.com',
          password: 'Onetwothree12@',
          retypePassword: 'Onetwothree12@',
          gender: 'MALE',
          dob: '1990-09-09',
          phoneNumber: '01911901234',
          address: 'Banani, Dhaka, Bangladesh'
        },
        {
          fullName: 'Malika Parvin',
          username: 'malikaparvin',
          email: 'malika.parvin@example.com',
          password: 'Onetwothree12@',
          retypePassword: 'Onetwothree12@',
          gender: 'FEMALE',
          dob: '1993-11-11',
          phoneNumber: '01912012345',
          address: 'Dhanmondi, Dhaka, Bangladesh'
        },
        {
          fullName: 'Sohel Rana',
          username: 'sohelrana',
          email: 'sohel.rana@example.com',
          password: 'Onetwothree12@',
          retypePassword: 'Onetwothree12@',
          gender: 'MALE',
          dob: '1988-04-04',
          phoneNumber: '01912123456',
          address: 'Mirpur, Dhaka, Bangladesh'
        },
        {
          fullName: 'Shirin Akter',
          username: 'shirinakter',
          email: 'shirin.akter@example.com',
          password: 'Onetwothree12@',
          retypePassword: 'Onetwothree12@',
          gender: 'FEMALE',
          dob: '1992-07-07',
          phoneNumber: '01912234567',
          address: 'Mohammadpur, Dhaka, Bangladesh'
        },
        {
          fullName: 'Adnan Ahmed',
          username: 'adnanaahmed',
          email: 'adnan.ahmed@example.com',
          password: 'Onetwothree12@',
          retypePassword: 'Onetwothree12@',
          gender: 'MALE',
          dob: '1989-11-11',
          phoneNumber: '01912345670',
          address: 'Uttara, Dhaka, Bangladesh'
        },
        {
          fullName: 'Moushumi Akhtar',
          username: 'moushumiakhtar',
          email: 'moushumi.akhtar@example.com',
          password: 'Onetwothree12@',
          retypePassword: 'Onetwothree12@',
          gender: 'FEMALE',
          dob: '1994-05-05',
          phoneNumber: '01912456781',
          address: 'Gulshan, Dhaka, Bangladesh'
        },
        {
          fullName: 'Mahmudul Hasan',
          username: 'mahmudulhasan',
          email: 'mahmudul.hasan@example.com',
          password: 'Onetwothree12@',
          retypePassword: 'Onetwothree12@',
          gender: 'MALE',
          dob: '1991-06-06',
          phoneNumber: '01912567892',
          address: 'Banani, Dhaka, Bangladesh'
        },
        {
          fullName: 'Sohana Sultana',
          username: 'sohanasultana',
          email: 'sohana.sultana@example.com',
          password: 'Onetwothree12@',
          retypePassword: 'Onetwothree12@',
          gender: 'FEMALE',
          dob: '1993-03-03',
          phoneNumber: '01912678903',
          address: 'Dhanmondi, Dhaka, Bangladesh'
        },
        {
          fullName: 'Imtiaz Rahman',
          username: 'imtiazrahman',
          email: 'imtiaz.rahman@example.com',
          password: 'Onetwothree12@',
          retypePassword: 'Onetwothree12@',
          gender: 'MALE',
          dob: '1987-12-12',
          phoneNumber: '01912789014',
          address: 'Mirpur, Dhaka, Bangladesh'
        },
        {
          fullName: 'Nusrat Begum',
          username: 'nusratbegum',
          email: 'nusrat.begum@example.com',
          password: 'Onetwothree12@',
          retypePassword: 'Onetwothree12@',
          gender: 'FEMALE',
          dob: '1990-02-02',
          phoneNumber: '01912890125',
          address: 'Mohammadpur, Dhaka, Bangladesh'
        },
        {
          fullName: 'Azad Hossain',
          username: 'azadhossain',
          email: 'azad.hossain@example.com',
          password: 'Onetwothree12@',
          retypePassword: 'Onetwothree12@',
          gender: 'MALE',
          dob: '1988-03-03',
          phoneNumber: '01912901236',
          address: 'Uttara, Dhaka, Bangladesh'
        },
        {
          fullName: 'Sultana Begum',
          username: 'sultanabegum',
          email: 'sultana.begum@example.com',
          password: 'Onetwothree12@',
          retypePassword: 'Onetwothree12@',
          gender: 'FEMALE',
          dob: '1992-10-10',
          phoneNumber: '01913012347',
          address: 'Gulshan, Dhaka, Bangladesh'
        },
        {
          fullName: 'Nazmul Islam',
          username: 'nazmulislam',
          email: 'nazmul.islam@example.com',
          password: 'Onetwothree12@',
          retypePassword: 'Onetwothree12@',
          gender: 'MALE',
          dob: '1989-09-09',
          phoneNumber: '01913123458',
          address: 'Banani, Dhaka, Bangladesh'
        },
        {
          fullName: 'Jennifer Lee',
          username: 'jenniferlee',
          email: 'jennifer.lee@example.com',
          password: 'Onetwothree12@',
          retypePassword: 'Onetwothree12@',
          gender: 'FEMALE',
          dob: '1995-01-01',
          phoneNumber: '01913234569',
          address: 'Dhanmondi, Dhaka, Bangladesh'
        },
        {
          fullName: 'Rajib Das',
          username: 'rajibdas',
          email: 'rajib.das@example.com',
          password: 'Onetwothree12@',
          retypePassword: 'Onetwothree12@',
          gender: 'MALE',
          dob: '1990-08-08',
          phoneNumber: '01913345670',
          address: 'Mirpur, Dhaka, Bangladesh'
        },
        {
          fullName: 'Sumi Chowdhury',
          username: 'sumichowdhury',
          email: 'sumi.chowdhury@example.com',
          password: 'Onetwothree12@',
          retypePassword: 'Onetwothree12@',
          gender: 'FEMALE',
          dob: '1993-11-11',
          phoneNumber: '01913456781',
          address: 'Mohammadpur, Dhaka, Bangladesh'
        },
        {
          fullName: 'Aslam Hossain',
          username: 'aslamhossain',
          email: 'aslam.hossain@example.com',
          password: 'Onetwothree12@',
          retypePassword: 'Onetwothree12@',
          gender: 'MALE',
          dob: '1988-06-06',
          phoneNumber: '01913567892',
          address: 'Uttara, Dhaka, Bangladesh'
        },
        {
          fullName: 'Anika Begum',
          username: 'anikabegum',
          email: 'anika.begum@example.com',
          password: 'Onetwothree12@',
          retypePassword: 'Onetwothree12@',
          gender: 'FEMALE',
          dob: '1992-04-04',
          phoneNumber: '01913678903',
          address: 'Gulshan, Dhaka, Bangladesh'
        },
        {
          fullName: 'Ehsanul Hoque',
          username: 'ehsanulhoque',
          email: 'ehsan.hoque@example.com',
          password: 'Onetwothree12@',
          retypePassword: 'Onetwothree12@',
          gender: 'MALE',
          dob: '1991-03-03',
          phoneNumber: '01913789014',
          address: 'Banani, Dhaka, Bangladesh'
        },
        {
          fullName: 'Farzana Begum',
          username: 'farzanabegum',
          email: 'farzana.begum@example.com',
          password: 'Onetwothree12@',
          retypePassword: 'Onetwothree12@',
          gender: 'FEMALE',
          dob: '1993-07-07',
          phoneNumber: '01913890125',
          address: 'Dhanmondi, Dhaka, Bangladesh'
        },
        {
          fullName: 'Ziaur Rahman',
          username: 'ziaurrahman',
          email: 'ziaur.rahman@example.com',
          password: 'Onetwothree12@',
          retypePassword: 'Onetwothree12@',
          gender: 'MALE',
          dob: '1987-10-10',
          phoneNumber: '01913901236',
          address: 'Mirpur, Dhaka, Bangladesh'
        },
        {
          fullName: 'Rumana Akter',
          username: 'rumanaakter',
          email: 'rumana.akter@example.com',
          password: 'Onetwothree12@',
          retypePassword: 'Onetwothree12@',
          gender: 'FEMALE',
          dob: '1995-05-05',
          phoneNumber: '01914012347',
          address: 'Mohammadpur, Dhaka, Bangladesh'
        }
      ];
      
}